name: Minify Workflow
on:
  pull_request:
    branches:
      - main 

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          maxdepth: 2
